# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Xin Tong
paginate:       15
baseurl:        ""
url:            "https://eagletongx.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# Gems
gems:
  - jekyll-paginate
